@startuml
class Compra {
    + Compra()
    + Compra(fechaCompra:DateTime, codigoDescuento:string?, metodoDePago:MetodosdePago, comprarItems:IList<ComprarItem>)
    + Id : int <<get>> <<set>>
    + PrecioTotal : double <<get>> <<set>>
    + CodigoDescuento : string? <<get>> <<set>>
    + FechaCompra : DateTime <<get>> <<set>>
    + ComprarItems : IList<ComprarItem> <<get>> <<set>>

}
class "IList`1"<T> {
}
Compra --> "ApplicationUser" ApplicationUser
Compra --> "MetodoDePago" MetodosdePago
@enduml
