@startuml
class Genero {
    + Genero()
    + Genero(id:int, nombre:string, libros:IList<Libro>)
    + Id : int <<get>> <<set>>
    + Nombre : string <<get>> <<set>>
    + Libros : IList<Libro> <<get>> <<set>>
}
@enduml
