@startuml
!include .\\ApplicationUser.puml
!include .\\Compra.puml
!include .\\ComprarItem.puml
!include .\\Editorial.puml
!include .\\Genero.puml
!include .\\Libro.puml
!include .\\Reposicion.puml
!include .\\ReposicionItem.puml
!include .\\Subasta.puml
!include .\\SubastaItem.puml
@enduml
