@startuml
class Reposicion {
    + Reposicion()
    + Reposicion(fechaReposicion:DateTime, comentario:string?, metodoDePago:MetodosdePago, reposicionItem:IList<ReposicionItem>)
    + Id : int <<get>> <<set>>
    + Comentario : string? <<get>> <<set>>
    + PrecioTotal : double <<get>> <<set>>
    + FechaReposicion : DateTime <<get>> <<set>>
    + ReposicionItems : IList<ReposicionItem> <<get>> <<set>>
}
class "IList`1"<T> {
}
Reposicion --> "MetodoDePago" MetodosdePago
Reposicion --> "ApplicationUser" ApplicationUser
@enduml
