@startuml
class SubastaItem {
    + SubastaItem()
    + SubastaItem(libro:Libro, subasta:Subasta, precioPuja:double, descripcion:string?)
    + PrecioPuja : double <<get>> <<set>>
    + Descripcion : string? <<get>> <<set>>
    + LibroId : int <<get>> <<set>>
    + SubastaId : int <<get>> <<set>>
}
SubastaItem --> "Libro" Libro
SubastaItem --> "Subasta" Subasta
@enduml
